var request = require("request");

var options = { method: 'PATCH',
  url: 'https://diksha.gov.in/action/assessment/v3/items/update/do_3126137118316625921514',
  headers: 
   { 'postman-token': '72b4dbc5-d970-100d-4a99-f3784e7016b2',
     'cache-control': 'no-cache',
     'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
     accept: '*/*',
     'accept-encoding': 'gzip, deflate, br',
     connection: 'keep-alive',
     'user-id': 'content-editor',
     cookie: 'connect.sid=s%3A4vw3oofkg8UaeWgw80YshyhBdSVg70bo.kDZAk93foSPUBCJoE%2F5xQUICL0qBlYOi0yD9ZW0gE9c',
     'content-type': 'application/json' },
  body: 
   { request: 
      { assessment_item: 
         { objectType: 'AssessmentItem',
           metadata: 
            { code: 'NA',
              isShuffleOption: false,
              body: '{"data":{"plugin":{"id":"org.ekstep.questionunit.mtf","version":"1.1","templateId":"horizontalMTF"},"data":{"question":{"text":"<p>Test content - SB-8368 - Not for usage - Delete after Nov - 1 - 2018 if you see</p>\\n","image":"","audio":"","audioName":"","hint":""},"option":{"optionsLHS":[{"text":"","image":"/assets/public/content/do_312607470374092800111945/artifact/1_1538997848501.png","audio":"","audioName":"","hint":"","index":1,"$$hashKey":"object:1211"},{"text":"","image":"/assets/public/content/do_312607470477189120111946/artifact/2_1538997861076.jpg","audio":"","audioName":"","hint":"","index":2,"$$hashKey":"object:1212"},{"text":"","image":"/assets/public/content/do_312607470587437056211710/artifact/3_1538997874626.jpg","audio":"","audioName":"","hint":"","index":3,"$$hashKey":"object:1213"}],"optionsRHS":[{"text":"","image":"/assets/public/content/14682375438131hi.png","audio":"","audioName":"","hint":"","mapIndex":1},{"text":"","image":"/assets/public/content/14670197953322hi.png","audio":"","audioName":"","hint":"","mapIndex":2},{"text":"","image":"/assets/public/content/14659031878293hi.png","audio":"","audioName":"","hint":"","mapIndex":3}],"questionCount":0},"media":[{"id":38313803,"src":"/assets/public/content/14682375438131hi.png","assetId":"do_30026277_onehand_i","type":"image","preload":false},{"id":336704757,"src":"/assets/public/content/14670197953322hi.png","assetId":"do_30019960_twohand_i","type":"image","preload":false},{"id":468520855,"src":"/assets/public/content/14659031878293hi.png","assetId":"domain_9097_threehand_i","type":"image","preload":false}]},"config":{"metadata":{"data":{"plugin":{"id":"org.ekstep.questionunit.mtf","version":"1.1","templateId":"horizontalMTF"},"data":{"question":{"text":"<p>Test content - SB-8368 - Not for usage - Delete after Nov - 1 - 2018 if you see</p>\\n","image":"","audio":"","audioName":"","hint":""},"option":{"optionsLHS":[{"text":"","image":"/assets/public/content/do_312607470374092800111945/artifact/1_1538997848501.png","audio":"","audioName":"","hint":"","index":1,"$$hashKey":"object:1211"},{"text":"","image":"/assets/public/content/do_312607470477189120111946/artifact/2_1538997861076.jpg","audio":"","audioName":"","hint":"","index":2,"$$hashKey":"object:1212"},{"text":"","image":"/assets/public/content/do_312607470587437056211710/artifact/3_1538997874626.jpg","audio":"","audioName":"","hint":"","index":3,"$$hashKey":"object:1213"}],"optionsRHS":[{"text":"","image":"/assets/public/content/14682375438131hi.png","audio":"","audioName":"","hint":"","mapIndex":1},{"text":"","image":"/assets/public/content/14670197953322hi.png","audio":"","audioName":"","hint":"","mapIndex":2},{"text":"","image":"/assets/public/content/14659031878293hi.png","audio":"","audioName":"","hint":"","mapIndex":3}],"questionCount":0},"media":[{"id":38313803,"src":"/assets/public/content/14682375438131hi.png","assetId":"do_30026277_onehand_i","type":"image","preload":false},{"id":336704757,"src":"/assets/public/content/14670197953322hi.png","assetId":"do_30019960_twohand_i","type":"image","preload":false},{"id":468520855,"src":"/assets/public/content/14659031878293hi.png","assetId":"domain_9097_threehand_i","type":"image","preload":false}]},"config":{"metadata":{"data":{"plugin":{"id":"org.ekstep.questionunit.mtf","version":"1.1","templateId":"horizontalMTF"},"data":{"question":{"text":"<p>Test content - SB-8368 - Not for usage - Delete after Nov - 1 - 2018 if you see</p>\\n","image":"","audio":"","audioName":"","hint":""},"option":{"optionsLHS":[{"text":"","image":"/assets/public/content/do_312607470374092800111945/artifact/1_1538997848501.png","audio":"","audioName":"","hint":"","index":1,"$$hashKey":"object:1211"},{"text":"","image":"/assets/public/content/do_312607470477189120111946/artifact/2_1538997861076.jpg","audio":"","audioName":"","hint":"","index":2,"$$hashKey":"object:1212"},{"text":"","image":"/assets/public/content/do_312607470587437056211710/artifact/3_1538997874626.jpg","audio":"","audioName":"","hint":"","index":3,"$$hashKey":"object:1213"}],"optionsRHS":[{"text":"","image":"/assets/public/content/14682375438131hi.png","audio":"","audioName":"","hint":"","mapIndex":1},{"text":"","image":"/assets/public/content/14670197953322hi.png","audio":"","audioName":"","hint":"","mapIndex":2},{"text":"","image":"/assets/public/content/14659031878293hi.png","audio":"","audioName":"","hint":"","mapIndex":3}],"questionCount":0},"media":[{"id":38313803,"src":"/assets/public/content/14682375438131hi.png","assetId":"do_30026277_onehand_i","type":"image","preload":false},{"id":336704757,"src":"/assets/public/content/14670197953322hi.png","assetId":"do_30019960_twohand_i","type":"image","preload":false},{"id":468520855,"src":"/assets/public/content/14659031878293hi.png","assetId":"domain_9097_threehand_i","type":"image","preload":false}]},"config":{"metadata":{"max_score":1,"isShuffleOption":false,"isPartialScore":true,"templateType":"Horizontal","name":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","title":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","board":"NCERT","medium":"English","gradeLevel":["Class 1"],"subject":"English","qlevel":"EASY","category":"MTF"},"max_time":0,"max_score":1,"partial_scoring":true,"layout":"Horizontal","isShuffleOption":false,"questionCount":1},"media":[{"id":38313803,"src":"/assets/public/content/14682375438131hi.png","assetId":"do_30026277_onehand_i","type":"image","preload":false},{"id":336704757,"src":"/assets/public/content/14670197953322hi.png","assetId":"do_30019960_twohand_i","type":"image","preload":false},{"id":468520855,"src":"/assets/public/content/14659031878293hi.png","assetId":"domain_9097_threehand_i","type":"image","preload":false}]},"medium":"English","questionTitle":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","qlevel":"EASY","subject":"English","board":"NCERT","templateType":"Horizontal","isPartialScore":true,"gradeLevel":["Class 1"],"isShuffleOption":false,"max_score":1,"name":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","title":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","category":"MTF"},"max_time":0,"max_score":1,"partial_scoring":true,"layout":"Horizontal","isShuffleOption":false,"questionCount":1},"media":[{"id":38313803,"src":"/assets/public/content/14682375438131hi.png","assetId":"do_30026277_onehand_i","type":"image","preload":false},{"id":336704757,"src":"/assets/public/content/14670197953322hi.png","assetId":"do_30019960_twohand_i","type":"image","preload":false},{"id":468520855,"src":"/assets/public/content/14659031878293hi.png","assetId":"domain_9097_threehand_i","type":"image","preload":false}]},"medium":"English","questionTitle":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","qlevel":"EASY","subject":"English","board":"NCERT","templateType":"Horizontal","isPartialScore":true,"gradeLevel":["Class 1"],"isShuffleOption":false,"max_score":1,"name":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","title":"SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see","category":"MTF"},"max_time":0,"max_score":1,"partial_scoring":true,"layout":"Horizontal","isShuffleOption":false,"questionCount":1},"media":[{"id":38313803,"src":"/assets/public/content/14682375438131hi.png","assetId":"do_30026277_onehand_i","type":"image","preload":false},{"id":336704757,"src":"/assets/public/content/14670197953322hi.png","assetId":"do_30019960_twohand_i","type":"image","preload":false},{"id":468520855,"src":"/assets/public/content/14659031878293hi.png","assetId":"domain_9097_threehand_i","type":"image","preload":false}]}}',
              itemType: 'UNIT',
              version: 2,
              category: 'MTF',
              createdBy: '0e0b5ca2-cdd4-42eb-9c91-f909e3f175f7',
              channel: '0123221758376673287017',
              type: 'mtf',
              template: 'NA',
              template_id: 'NA',
              framework: 'NCF',
              data: 
               { plugin: 
                  { id: 'org.ekstep.questionunit.mtf',
                    version: '1.1',
                    templateId: 'horizontalMTF' },
                 data: 
                  { question: 
                     { text: '<p>Test content - SB-8368 - Not for usage - Delete after Nov - 1 - 2018 if you see</p>\n',
                       image: '',
                       audio: '',
                       audioName: '',
                       hint: '' },
                    option: 
                     { optionsLHS: 
                        [ { text: '',
                            image: '/assets/public/content/do_312607470374092800111945/artifact/1_1538997848501.png',
                            audio: '',
                            audioName: '',
                            hint: '',
                            index: 1,
                            '$$hashKey': 'object:1211' },
                          { text: '',
                            image: '/assets/public/content/do_312607470477189120111946/artifact/2_1538997861076.jpg',
                            audio: '',
                            audioName: '',
                            hint: '',
                            index: 2,
                            '$$hashKey': 'object:1212' },
                          { text: '',
                            image: '/assets/public/content/do_312607470587437056211710/artifact/3_1538997874626.jpg',
                            audio: '',
                            audioName: '',
                            hint: '',
                            index: 3,
                            '$$hashKey': 'object:1213' } ],
                       optionsRHS: 
                        [ { text: '',
                            image: '/assets/public/content/14682375438131hi.png',
                            audio: '',
                            audioName: '',
                            hint: '',
                            mapIndex: 1 },
                          { text: '',
                            image: '/assets/public/content/14670197953322hi.png',
                            audio: '',
                            audioName: '',
                            hint: '',
                            mapIndex: 2 },
                          { text: '',
                            image: '/assets/public/content/14659031878293hi.png',
                            audio: '',
                            audioName: '',
                            hint: '',
                            mapIndex: 3 } ],
                       questionCount: 0 },
                    media: 
                     [ { id: 38313803,
                         src: '/assets/public/content/14682375438131hi.png',
                         assetId: 'do_30026277_onehand_i',
                         type: 'image',
                         preload: false },
                       { id: 336704757,
                         src: '/assets/public/content/14670197953322hi.png',
                         assetId: 'do_30019960_twohand_i',
                         type: 'image',
                         preload: false },
                       { id: 468520855,
                         src: '/assets/public/content/14659031878293hi.png',
                         assetId: 'domain_9097_threehand_i',
                         type: 'image',
                         preload: false } ] },
                 config: 
                  { metadata: 
                     { data: 
                        { plugin: 
                           { id: 'org.ekstep.questionunit.mtf',
                             version: '1.1',
                             templateId: 'horizontalMTF' },
                          data: 
                           { question: 
                              { text: '<p>Test content - SB-8368 - Not for usage - Delete after Nov - 1 - 2018 if you see</p>\n',
                                image: '',
                                audio: '',
                                audioName: '',
                                hint: '' },
                             option: 
                              { optionsLHS: 
                                 [ { text: '',
                                     image: '/assets/public/content/do_312607470374092800111945/artifact/1_1538997848501.png',
                                     audio: '',
                                     audioName: '',
                                     hint: '',
                                     index: 1,
                                     '$$hashKey': 'object:1211' },
                                   { text: '',
                                     image: '/assets/public/content/do_312607470477189120111946/artifact/2_1538997861076.jpg',
                                     audio: '',
                                     audioName: '',
                                     hint: '',
                                     index: 2,
                                     '$$hashKey': 'object:1212' },
                                   { text: '',
                                     image: '/assets/public/content/do_312607470587437056211710/artifact/3_1538997874626.jpg',
                                     audio: '',
                                     audioName: '',
                                     hint: '',
                                     index: 3,
                                     '$$hashKey': 'object:1213' } ],
                                optionsRHS: 
                                 [ { text: '',
                                     image: '/assets/public/content/14682375438131hi.png',
                                     audio: '',
                                     audioName: '',
                                     hint: '',
                                     mapIndex: 1 },
                                   { text: '',
                                     image: '/assets/public/content/14670197953322hi.png',
                                     audio: '',
                                     audioName: '',
                                     hint: '',
                                     mapIndex: 2 },
                                   { text: '',
                                     image: '/assets/public/content/14659031878293hi.png',
                                     audio: '',
                                     audioName: '',
                                     hint: '',
                                     mapIndex: 3 } ],
                                questionCount: 0 },
                             media: 
                              [ { id: 38313803,
                                  src: '/assets/public/content/14682375438131hi.png',
                                  assetId: 'do_30026277_onehand_i',
                                  type: 'image',
                                  preload: false },
                                { id: 336704757,
                                  src: '/assets/public/content/14670197953322hi.png',
                                  assetId: 'do_30019960_twohand_i',
                                  type: 'image',
                                  preload: false },
                                { id: 468520855,
                                  src: '/assets/public/content/14659031878293hi.png',
                                  assetId: 'domain_9097_threehand_i',
                                  type: 'image',
                                  preload: false } ] },
                          config: 
                           { metadata: 
                              { max_score: 1,
                                isShuffleOption: false,
                                isPartialScore: true,
                                templateType: 'Horizontal',
                                name: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
                                title: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
                                board: 'NCERT',
                                medium: 'English',
                                gradeLevel: [ 'Class 1' ],
                                subject: 'English',
                                qlevel: 'EASY',
                                category: 'MTF' },
                             max_time: 0,
                             max_score: 1,
                             partial_scoring: true,
                             layout: 'Horizontal',
                             isShuffleOption: false,
                             questionCount: 1 },
                          media: 
                           [ { id: 38313803,
                               src: '/assets/public/content/14682375438131hi.png',
                               assetId: 'do_30026277_onehand_i',
                               type: 'image',
                               preload: false },
                             { id: 336704757,
                               src: '/assets/public/content/14670197953322hi.png',
                               assetId: 'do_30019960_twohand_i',
                               type: 'image',
                               preload: false },
                             { id: 468520855,
                               src: '/assets/public/content/14659031878293hi.png',
                               assetId: 'domain_9097_threehand_i',
                               type: 'image',
                               preload: false } ] },
                       medium: 'English',
                       questionTitle: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
                       qlevel: 'EASY',
                       subject: 'English',
                       board: 'NCERT',
                       templateType: 'Horizontal',
                       isPartialScore: true,
                       gradeLevel: [ 'Class 1' ],
                       isShuffleOption: false,
                       max_score: 1,
                       name: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
                       title: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
                       category: 'MTF' },
                    max_time: 0,
                    max_score: 1,
                    partial_scoring: true,
                    layout: 'Horizontal',
                    isShuffleOption: false,
                    questionCount: 1 },
                 media: 
                  [ { id: 38313803,
                      src: '/assets/public/content/14682375438131hi.png',
                      assetId: 'do_30026277_onehand_i',
                      type: 'image',
                      preload: false },
                    { id: 336704757,
                      src: '/assets/public/content/14670197953322hi.png',
                      assetId: 'do_30019960_twohand_i',
                      type: 'image',
                      preload: false },
                    { id: 468520855,
                      src: '/assets/public/content/14659031878293hi.png',
                      assetId: 'domain_9097_threehand_i',
                      type: 'image',
                      preload: false } ] },
              medium: 'English',
              questionTitle: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
              qlevel: 'EASY',
              subject: 'English',
              board: 'NCERT',
              templateType: 'Horizontal',
              isPartialScore: true,
              gradeLevel: [ 'Class 1' ],
              max_score: 1,
              name: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
              title: 'SB-8368 - Test Content - Not for usage - Delete after Nov - 1 - 2018 if you see',
              lhs_options: 
               [ { value: 
                    { type: 'mixed',
                      text: 'इक',
                      image: '',
                      count: '',
                      audio: '',
                      resvalue: 'इक',
                      resindex: 0 },
                   index: 0 } ],
              rhs_options: 
               [ { value: 
                    { type: 'mixed',
                      text: 'इक',
                      image: '',
                      count: '',
                      audio: '',
                      resvalue: 'इक',
                      resindex: 0 },
                   index: 0 } ] },
           outRelations: [] } } },
  json: true };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
